export default {
    consultants: [{
            "name": "孙磊",
            "name_en": "TOM SUN",
            "email": "",
            "position": "外包业务负责人",
            "location": "上海",
            "date": "2019-9-16",
            "description": "曾就职于中软，东南融通，文思海辉，佰钧成等国内一流IT外包公司，并担任重要管理职位。同时，在Microsoft，Criteo等国际知名IT企业任职过。拥有丰富的IT，外包全行业的经验。",
            "experience1": "中软，东南融通，文思海辉，佰钧成等国内一流IT外包公司",
            "experience2": "Microsoft，Criteo等国际知名IT企业",
            "experience3": "",
            "field1": "IT",
            "field2": "全行业",
            "field3": "",
            "keyword1": "外包业务负责人",
            "keyword2": "外包全行业",
            "keyword3": "",
            "keyword4": "",
            "education1": "",
            "education2": "",
            "status": "有效",
            "id": 7,
            "imgUrl": require('../../assets/images/avatars/孙磊.jpg')
        },
        {
            "name": "樊申哲",
            "name_en": "LESLIE",
            "email": "",
            "position": "猎头业务合伙人",
            "location": "上海",
            "date": "2019-9-16",
            "description": "拥有十余年德资企业管理经验，交通大学工商管理学硕士，具有五维教练领导力认证。进入猎头行业带团队四年，率领大制造行业团队连续三年年业绩增长50%，善于培养百万顾问，其中四个顾问都成为公司中、高层管理人员",
            "experience1": "十余年德资企业管理层经验",
            "experience2": "海德堡销售总监",
            "experience3": "CIPC注册国际心理咨询师",
            "field1": "制造业",
            "field2": "德资",
            "field3": "",
            "keyword1": "销售总监",
            "keyword2": "领导力",
            "keyword3": "",
            "keyword4": "",
            "education1": "交通大学本科",
            "education2": "交通大学工商管理学硕士",
            "status": "有效",
            "id": 5,
            "imgUrl": require('../../assets/images/avatars/樊申哲.jpg')
        },
        {
            "name": "汤晓烨",
            "name_en": "VERA",
            "email": "",
            "position": "猎头业务合伙人",
            "location": "上海",
            "date": "2019-9-16",
            "description": "于14年以管培生身份加入择仕，连续3年百万顾问及公司TOP 1，4年连续晋升。南开大学应用心理学硕士。连续多次季度最佳业绩。斩获公司十多项嘉奖。带领团队成员单产年均75万",
            "experience1": "多次季度最佳业绩",
            "experience2": "连续3年百万顾问及公司TOP 1",
            "experience3": "团队成员单产年均75万",
            "field1": "互联网行业",
            "field2": "",
            "field3": "",
            "keyword1": "资深顾问",
            "keyword2": "百万顾问",
            "keyword3": "",
            "keyword4": "",
            "education1": "南开大学应用心理学硕士",
            "education2": "",
            "status": "有效",
            "id": 6,
            "imgUrl": require('../../assets/images/avatars/汤晓烨.jpg')
        },
        {
            "name": "火颖杰",
            "name_en": "JASON",
            "email": "",
            "position": "猎头业务合伙人",
            "location": "上海",
            "date": "2019-9-16",
            "description": "曾就职于瀚德、Michaelpage等大型外资猎头公司，同济大学本科，在瀚德就职期间年最高单产230万，2018年获择仕最高单笔业绩个人佣金60万。团队业绩五百万TeamLeader",
            "experience1": "瀚德、Michaelpage等大型外资猎头公司",
            "experience2": "最高单产230万",
            "experience3": "团队业绩五百万TeamLeader",
            "field1": "消费品行业",
            "field2": "",
            "field3": "",
            "keyword1": "百万级Leader",
            "keyword2": "资深猎头",
            "keyword3": "",
            "keyword4": "",
            "education1": "同济大学本科",
            "education2": "",
            "status": "有效",
            "id": 8,
            "imgUrl": require('../../assets/images/avatars/火颖杰.jpg')
        },
        {
            "name": "张楠",
            "name_en": "ELLA",
            "email": "",
            "position": "区域合伙人",
            "location": "上海",
            "date": "2019-9-16",
            "description": " 拥有十年人力资源行业从业经验，曾任西北地区独角兽Yeahmobi集团核心高管带领择仕中国西安团队拿下多家北京、西北地区互联网头部客户，巩固择仕中国位于西北板块业务发展。",
            "experience1": "十年人力资源行业从业经验",
            "experience2": "曾任西北地区独角兽Yeahmobi集团核心高管",
            "experience3": "",
            "field1": "互联网行业",
            "field2": "",
            "field3": "",
            "keyword1": "核心高管",
            "keyword2": "十年经验",
            "keyword3": "",
            "keyword4": "",
            "education1": "",
            "education2": "",
            "status": "有效",
            "id": 9,
            "imgUrl": require('../../assets/images/avatars/张楠.jpg')
        },
    ]
}