export default {
    jobs: [
        // {
        //     id: "2019101101",
        //     date: "2019/10/11",
        //     email: "chuckxu@versal.com.cn",
        //     title: "IT应用工程师",
        //     location: "上海",
        //     company: "华培动力",
        //     type: " IT应用工程师",
        //     category: "汽车零部件",
        //     salary: "20W",
        //     description: "IT应用工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "具有OA泛微系统维护经验",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101102",
        //     date: "2019/10/11",
        //     email: "chuckxu@versal.com.cn",
        //     title: "销售经理",
        //     location: "台州",
        //     company: "维艾尔工业",
        //     type: "销售经理",
        //     category: "消费品",
        //     salary: "15~20K",
        //     description: "销售经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "消费品行业商超渠道经验，大客户管理经验",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101103",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: " Account Manager",
        //     location: "上海",
        //     company: "华培动力",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "20w~25W",
        //     description: " Account Manager",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "3~5年汽车零部件销售经验，熟悉一级供应商，或者主机厂流程。",
        //     request2: "具备一定的英语口语能力",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101104",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: "销售经理",
        //     location: "上海",
        //     company: "ITW",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "面议",
        //     description: "销售经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "具有对接通用以及通用Tier1的服务经验",
        //     request2: "80后，男性",
        //     request3: "具有汽配行业8年销售经验",
        //     request4: "具有4个人或以上的团队管理经验",
        //     request5: "优先考虑熟悉塑料汽车零部件产品",
        //     company_name: "",
        //     company_address: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101105",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: "重点客户销售",
        //     location: "上海",
        //     company: "ITW",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "面议",
        //     description: "重点客户销售",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "具有对接通用以及通用Tier1的服务经验",
        //     request2: "80后，男性",
        //     request3: "",
        //     request4: "具有汽配行业5年销售经验",
        //     request5: "优先考虑熟悉塑料汽车零部件产品",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101106",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: "客户经理",
        //     location: "上海",
        //     company: "ITW",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "面议",
        //     description: "客户经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "具有汽车内饰行业经验",
        //     request2: "具有3年以上汽配销售经验",
        //     request3: "熟悉塑料汽车零部件产品优先考虑",
        //     request4: "熟悉Tier1 ，Tier2的沟通模式",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101107",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: "销售经理",
        //     location: "上海",
        //     company: "上汽英飞凌",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "面议",
        //     description: "销售经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "具有对接OEM和Tier1 工作经验或服务经验",
        //     request2: "对政府市场政策了解",
        //     request3: "了解新能源市场及竞争对手",
        //     request4: "对工厂流程熟悉",
        //     request5: "熟悉合资公司运营",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101108",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: "CEO",
        //     location: "香港",
        //     company: "万安集团 ",
        //     type: "管理",
        //     category: "食品",
        //     salary: "HKD 200~400万",
        //     description: "CEO",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "香港当地人，或者香港居住的外籍人士",
        //     request2: "对冷冻食品行业熟悉",
        //     request3: "有丰富的P&L的管理经验",
        //     request4: "销售或者供应链出身为佳",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101109",
        //     date: "2019/10/11",
        //     email: "jasonhuo@versal.com.cn",
        //     title: "总经理",
        //     location: "上海",
        //     company: "成长型精密铸造设备公司",
        //     type: "管理",
        //     category: "紧密铸造",
        //     salary: "100万人民币",
        //     description: "总经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "熟悉真空熔炼、重力铸造、吸柱、差压设备等技术",
        //     request2: "人民币100万左右",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101110",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "软件工程师",
        //     location: "上海",
        //     company: "空调国际",
        //     type: "软件",
        //     category: "汽车空调",
        //     salary: "20W",
        //     description: "软件工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "懂得运用招聘软件，熟练运用matlab，C，CAN等技术",
        //     request2: "具有三年左右的工作经验",
        //     request3: "学历大专以上",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101111",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "雷达算法软件开发工程师",
        //     location: "上海",
        //     company: "华域汽车",
        //     type: "软件",
        //     category: "汽车零部件",
        //     salary: "不限",
        //     description: "雷达算法软件开发工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "熟悉雷达算法",
        //     request2: "信号处理 2-3名，数据处理1-2名，机器视觉1名",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101112",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "软件开发工程师",
        //     location: "上海",
        //     company: "安波福",
        //     type: "软件",
        //     category: "汽车零部件",
        //     salary: "30W以内",
        //     description: "软件开发工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "熟悉仿真或诊断",
        //     request2: "熟悉matlab和C的手写代码",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101113",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "车载软件架构师",
        //     location: "上海",
        //     company: "斑马网络",
        //     type: "软件",
        //     category: "互联网",
        //     salary: "不限",
        //     description: "车载软件架构师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "具有汽车行业的工作经验",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101114",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "多媒体技术专家",
        //     location: "上海",
        //     company: "斑马网络",
        //     type: "软件",
        //     category: "互联网",
        //     salary: "不限",
        //     description: "多媒体技术专家",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "学历硕士以上",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101115",
        //     date: "2019/10/12",
        //     email: "wendycao@versal.com.cn",
        //     title: "语音技术专家",
        //     location: "上海",
        //     company: "斑马网络",
        //     type: "软件",
        //     category: "互联网",
        //     salary: "60W",
        //     description: "语音技术专家",
        //     duty1: "负责AliOS车载娱乐系统中语音业务开发",
        //     duty2: "对话系统DM、本地和云端仲裁、业务场景设计、数据服务对接等业务开发",
        //     duty3: "多引擎的对接适配",
        //     duty4: "良好的架构设计、系统思维、主动解决问题的能力",
        //     duty5: "",
        //     request1: "学历硕士以上",
        //     request2: "计算机、通信、自动化或电子工程专业本科及以上学历；",
        //     request3: "扎实的C/C++语言基础，有很强的编码能力,熟悉Linux开发平台；",
        //     request4: "学习能力强，良好的沟通表达和理解能力，团队精神；",
        //     request5: "加分项:1）车载娱乐系统开发经验;2）熟悉语音识别/机器学习/自然语言处理相关概念的;3）熟悉车载音频相关模块;4) 熟悉NodeJS",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101116",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: " 软件工程师",
        //     location: "上海",
        //     company: "博世华域汽车",
        //     type: "软件",
        //     category: "汽车零部件",
        //     salary: "面议",
        //     description: " 软件工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "熟悉偏向底盘件的工作经验",
        //     request2: "具有完整的复杂驱动经验",
        //     request3: "熟悉MCU和mcal的开发",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101117",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "蓝牙软件工程师",
        //     location: "上海",
        //     company: "福瑞泰克",
        //     type: "软件",
        //     category: "汽车电器",
        //     salary: "40W以内",
        //     description: "蓝牙软件工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "有汽车行业工作经验",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101118",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "软件开发工程师",
        //     location: "上海",
        //     company: "科世达",
        //     type: "软件",
        //     category: "汽车",
        //     salary: "不限",
        //     description: "软件开发工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "熟悉adas的L4开发",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101119",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "电气工程师",
        //     location: "上海",
        //     company: "荣泰",
        //     type: "电气",
        //     category: "",
        //     salary: "6K~12K",
        //     description: "",
        //     duty1: "电气设计标准制定与维护；",
        //     duty2: "根据项目设计需求，制定电气线束方案，并产出设计；",
        //     duty3: "检查打样线束过程中材料的规格、品牌、技术性能等；",
        //     duty4: "建立、完善电气图纸的档案、统计、编号等。",
        //     duty5: "",
        //     request1: "学历: 不限制",
        //     request2: "熟练使用CAD、CAXA等画图软件、WPS office办公软件，懂电子电路，会焊接电路板，熟悉电子、电气加工工艺和维修的技术知识，现场管理知识；",
        //     request3: "本岗位工作经验3年及以上，从事按摩椅行业本岗位经验者优先。",
        //     request4: "能吃苦耐劳，善于沟通、工作认真负责、服从上级领导安排、团队精神优良。",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101120",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "资深软件开发",
        //     location: "上海",
        //     company: "英纳法",
        //     type: "软件",
        //     category: "",
        //     salary: "30W以内",
        //     description: "资深软件开发",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101121",
        //     date: "2019/10/11",
        //     email: "wendycao@versal.com.cn",
        //     title: "Business Analyst – Finance and Reporting",
        //     location: "上海",
        //     company: "英纳法",
        //     type: "财务",
        //     category: "",
        //     salary: "30W以内",
        //     description: "Business Analyst – Finance and Reporting",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101122",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "Product Engineer",
        //     location: "上海",
        //     company: "ITW",
        //     type: "",
        //     category: "汽车零部件",
        //     salary: "20W~30W",
        //     description: "紧固件产品工程师",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "4年以上EV高压线束设计开发经验",
        //     request2: "熟悉塑料紧固件产品",
        //     request3: "英文可以作为工作语言",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101123",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "冷却系统开发工程师",
        //     location: "上海",
        //     company: "马勒热",
        //     type: "",
        //     category: "汽车零部件",
        //     salary: "20W~30W",
        //     description: "Product Engineer",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "熟悉塑料紧固件产品",
        //     request2: "有日系客户项目产品开发经验",
        //     request3: "英文可以作为工作语言",
        //     request4: "5年左右产品设计开发经验",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101124",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "中国区研发总监",
        //     location: "上海",
        //     company: "现代摩比斯",
        //     type: "管理",
        //     category: "汽车零部件",
        //     salary: "100W",
        //     description: "中国区研发总监",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "15年以上乘用车底盘（制动或转向）或车灯开发经验",
        //     request2: "英文口语流利",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101125",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "Account Manager",
        //     location: "上海",
        //     company: "ZAT",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "25W-30W",
        //     description: "Account Manager",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "3年或以上汽车零部件销售经验",
        //     request2: "热爱挑战",
        //     request3: "有成功主机厂报价经验",
        //     request4: "能适应一定强度出差",
        //     request5: "英文口语流利",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101126",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "Project Manager",
        //     location: "上海",
        //     company: "BHTC",
        //     type: "项目管理",
        //     category: "汽车零部件",
        //     salary: "25W-30W",
        //     description: "Account Manager",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "3年或以上汽车零部件销售经验",
        //     request2: "有成功主机厂报价经验",
        //     request3: "英文口语流利",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101127",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "Sales Engineer",
        //     location: "北京",
        //     company: "ZAT",
        //     type: "销售",
        //     category: "汽车零部件",
        //     salary: "20W-30W",
        //     description: "Sales Engineer",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "工科背景",
        //     request2: "男性",
        //     request3: "英文听说流利",
        //     request4: "汽车行业销售3年或以上的销售经验",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101128",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "National Sales Manager",
        //     location: "上海",
        //     company: "莱丹塑料焊接",
        //     type: "销售管理",
        //     category: "工业制造",
        //     salary: "50~60W",
        //     description: "全国销售经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        // {
        //     id: "2019101129",
        //     date: "2019/10/11",
        //     email: "crystalyan@versal.com.cn",
        //     title: "上市公司总经理",
        //     location: "上海",
        //     company: "华培动力 ",
        //     type: "运营管理",
        //     category: "工业制造",
        //     salary: "80~100W",
        //     description: "总经理",
        //     duty1: "",
        //     duty2: "",
        //     duty3: "",
        //     duty4: "",
        //     duty5: "",
        //     request1: "",
        //     request2: "",
        //     request3: "",
        //     request4: "",
        //     request5: "",
        //     company_name: "",
        //     company_name: "",
        //     company_description: "",
        //     status: ""
        // },
        {
            id: "2019101130",
            date: "2019/10/11",
            email: "crystalyan@versal.com.cn",
            title: "Program Manager",
            location: "上海",
            company: "盖瑞特",
            type: "项目管理",
            category: "汽车零部件",
            salary: "35-45W",
            description: "Program Manager",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "",
            request2: "",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101131",
            date: "2019/10/11",
            email: "crystalyan@versal.com.cn",
            title: "BD Manager",
            location: "上海",
            company: "Ecoclean",
            type: "管理",
            category: "工业制造",
            salary: "底薪+提成",
            description: "BD Manager",
            duty1: "为完成业绩指标，在行业内发掘潜在客户和业务，并定期客户拜访，做好客户关系维护;为待报价项目做风险分析评估;销售方面根据公司规定进行的报价准备（内容提要，价格，付款条件）;和客户进行合同条款及终验收条件的谈判，为公司赢得最大化利益 ;项目启动会议后的会议纪要的确认并进行订单审核 ;支持新项目的运作的计划制定 ",
            duty2: "销售报表/计划管理:提供年度销售执行计划方案，包括销售目标，已知项目和执行情况等;按时提交销售报告，比如客户拜访报告，周报;制定周工作计划，定期完成工作总结，并及时提交至上级领导 ",
            duty3: "为实现团队目标，技术分享、市场信息和竞争对手信息分享 ",
            duty4: "执行领导布置的其他相关工作  ",
            duty5: "",
            request1: "",
            request2: "",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101132",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "产品经理",
            location: "上海",
            company: "上海新泓汽车零部件公司",
            type: "管理",
            category: "汽车零部件",
            salary: "18k-20k",
            description: "产品经理",
            duty1: "负责产品线软、硬件平台开发的构建，开发规范和标准的建立",
            duty2: "负责电子元器件库的建立和模块化设计工作",
            duty3: "负责设计系统框图，编写功能定义，输入至软件及硬件工程师",
            duty4: "负责产品线新技术的研究定义",
            duty5: "带领指导监督团队完成新产品和新技术的开发工作以及负责团队的专业能力建设",
            request1: "3年以上汽车电子行业相关经验",
            request2: " 熟悉AutoSar、Osek或其它软件架构及应用 ",
            request3: "熟悉LIN通信及CAN通讯",
            request4: "具备汽车电子软硬件开发能力",
            request5: "具备ECU开发经验，有电动尾门控制器开发经验优先考虑",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101133",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "软件工程师(HMI)",
            location: "上海",
            company: "贝洱海拉温控系统（上海）有限公司",
            type: "软件",
            category: "汽车零部件",
            salary: "20W-25W",
            description: "软件工程师(HMI)",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "本科学历（211 985）",
            request2: " 英语流利 ",
            request3: "会使用C语言（应用层）软性素质好",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101134",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "电气系统工程师(HMI)",
            location: "上海",
            company: "贝洱海拉温控系统（上海）有限公司",
            type: "",
            category: "汽车零部件",
            salary: "30W-35W",
            description: "电气系统工程师(HMI)",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "本科学历（211 985）",
            request2: " 英语流利 ",
            request3: "会使用C语言（底层）偏软件方向多一些",
            request4: "懂得V模型开发使用 软性沟通要好",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101135",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "高级软件工程师(DPC)",
            location: "上海",
            company: "贝洱海拉温控系统（上海）有限公司",
            type: "",
            category: "汽车零部件",
            salary: "30W-35W",
            description: "高级软件工程师(DPC)",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "本科学历（211 985）",
            request2: " 英语流利 ",
            request3: "5年以上经验 ",
            request4: "会使用C语言（底层）",
            request5: "懂底层嵌入式开发",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101136",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "OA应用工程师",
            location: "上海",
            company: "华培动力 ",
            type: "",
            category: "汽车",
            salary: "16K-18K",
            description: "OA应用工程师",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "熟悉泛微系统的运维以及相关建模工作",
            request2: "",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101137",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "项目总监",
            location: "上海",
            company: "纳恩汽车技术",
            type: "",
            category: "汽车",
            salary: "面议",
            description: "项目总监",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "汽车零配件公司项目经验",
            request2: "有管理团队的经验",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101138",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "内外饰销售总监",
            location: "上海",
            company: "上海新泓汽车零部件公司 ",
            type: "",
            category: "汽车零部件",
            salary: "30K",
            description: "内外饰销售总监",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "汽车零配件公司销售经验",
            request2: "有管理团队的经验",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101139",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "销售工程师",
            location: "上海",
            company: "博泽",
            type: "销售",
            category: "",
            salary: "base 20K",
            description: "销售工程师",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "汽车零配件公司销售经验",
            request2: "熟悉吉利",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101140",
            date: "2019/10/11",
            email: "fionachen@versal.com.cn",
            title: "高级软件驱动工程师",
            location: "",
            company: "纳恩汽车",
            type: "",
            category: "",
            salary: "",
            description: "高级软件驱动工程师",
            duty1: "从事汽车电子模块的嵌入式软件开发；",
            duty2: "能正确分析系统需求，根据架构设计和实现软件模块和子系统；",
            duty3: "在产品生命周期内对软件模块和子系统进行调试、测试、维护和故障排除；",
            duty4: "参与软件设计和代码实现的评审；",
            duty5: "与项目团队保持良好沟通，对项目组和系统组的工作提供必要的支持；完成部门经理安排的其他工作。",
            request1: "精通Power PC、ARM、Freescale 16位、32位MCU底层驱动开发",
            request2: "精通C语言嵌入式开发",
            request3: "有PEPS、BCM开发经验者优先，有整个软件项目周期开发经验者优先",
            request4: "熟悉汽车总线通信和诊断协议（如CAN、LIN、UDS等）",
            request5: "5年以上工作经验",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101141",
            date: "2019/10/11",
            email: "Hammondhuang@versal.com.cn",
            title: "大客户总监",
            location: "北上广",
            company: "易车公司",
            type: "销售管理",
            category: "",
            salary: "50W-80W",
            description: "大客户总监",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "有主机厂背景资源且拥有广告销售经验",
            request2: "",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101142",
            date: "2019/10/11",
            email: "Amandaguan@versal.com.cn",
            title: "电商运营总监",
            location: "浙江",
            company: "浙江三门维艾尔工业有限公司",
            type: "电商",
            category: "",
            salary: "40W（可谈股份）",
            description: "电商运营总监",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "5年及以上电商运营经验",
            request2: "30-39岁",
            request3: "有线下经销商资源更好",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101143",
            date: "2019/10/11",
            email: "Amandaguan@versal.com.cn",
            title: "KA",
            location: "北上广",
            company: "日本软银集团",
            type: "",
            category: "",
            salary: "60W起步",
            description: "KA",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "了解酒店行业（有为酒店提供服务的经验）",
            request2: "很强的沟通能力， 社交能力，逼格高，BD能力强，人脉资源丰富",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101144",
            date: "2019/10/11",
            email: "Amandaguan@versal.com.cn",
            title: "CTO",
            location: "",
            company: "图匠科技",
            type: "AI智能 机器学习 深度学习",
            category: "",
            salary: "150万-300万",
            description: "CTO",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "AI人工智能 机器学习 深度学习 技术出身",
            request2: "硕士及以上 ",
            request3: "拥有综合管理团队经验",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101145",
            date: "2019/10/11",
            email: "Miafu@versal.com.cn",
            title: "电商运营总监",
            location: "浙江",
            company: "浙江三门维艾尔工业有限公司",
            type: "电商",
            category: "",
            salary: "40W（可谈股份）",
            description: "电商运营总监",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "5年及以上电商运营经验",
            request2: "30-39岁",
            request3: "有线下经销商资源更好",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101146",
            date: "2019/10/11",
            email: "Miafu@versal.com.cn",
            title: "KA",
            location: "北上广",
            company: "日本软银集团",
            type: "销售",
            category: "",
            salary: "60W起步",
            description: "KA",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "了解酒店行业（有为酒店提供服务的经验）",
            request2: "很强的沟通能力， 社交能力，逼格高，BD能力强，人脉资源丰富",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
        {
            id: "2019101147",
            date: "2019/10/11",
            email: "Miafu@versal.com.cn",
            title: "KA",
            location: "北上广",
            company: "日本软银集团",
            type: "销售",
            category: "",
            salary: "60W起步",
            description: "KA",
            duty1: "",
            duty2: "",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "有政府和地产资源",
            request2: "很强的沟通能力， 社交能力，逼格高，BD能力强，人脉资源丰富",
            request3: "",
            request4: "",
            request5: "",
            company_name: "美国维益食品公司",
            company_name: "",
            company_description: "创立于1945年的美国维益食品公司，是全球植脂奶油的创始者，也是美国最大的家族型冷冻食品制造商之一。",
            status: ""
        },
        {
            id: "2019101148",
            date: "2019/10/11",
            email: "Miafu@versal.com.cn",
            title: "华东区销售经理",
            location: "上海",
            company: "美国维益食品公司",
            type: "销售",
            category: "",
            salary: "暂无",
            description: "华东区销售经理",
            duty1: "带12个人的团队,一半销售,一半技术服务团队",
            duty2: "管理区域茶饮渠道(例如coco,喜茶等),饮品原材料的供应,汇报给全国茶饮渠道商务总监",
            duty3: "",
            duty4: "",
            duty5: "",
            request1: "有团队管理能力,对茶饮行业熟悉",
            request2: "业务能力强,丰富的bd经验,乐于奋斗",
            request3: "",
            request4: "",
            request5: "",
            company_name: "",
            company_name: "",
            company_description: "",
            status: ""
        },
    ]
}